resolver: lts-7.14
flags:
  pursuit:
    dev: true
packages:
- '.'
- location:
    git: https://github.com/purescript/purescript
    commit: ae3aa4d156be23dbb0f1c602ee408af47bb0d141
  extra-dep: true
extra-deps:
- barrier-0.1.1
- purescript-0.10.5
- bower-json-1.0.0.1
